### PR TITLE
Update swagger.yaml

### PR DESCRIPTION
**Pull request by odungern**
Oliver, I have made changes to dataTypes and hierarchies according to my proposals. Idea is to use the terms of the schema and no others. What do you think?  
In particular:
- I have not yet added the projects to the path ... 
- I have removed the revisions from it in favor of a query string. The idea is that specifying a revision is sort of filtering. We could also filter for types, classes or similar.

### CODE REVIEW

**Comment by oalt** [comment]
Hi Oskar!

I have read some guidelines about web api design before I started the definition. These guidelines all point in the same direction. 
Have a look e.g. at https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md and let us discuss this in our telco on Tuesday.

Regards

Oliver

**Comment by odungern** [comment]
Hallo, Oliver,
... yes, let's talk. I have invited for _Monday_, now, since I have found out that there is another SpecIF-telco on Tuesday. I hope Monday works out for you.
With respect to the API, I would like to have a close similarity between the terms in the schema and the API. If the current terms as used in the schema are not so good for the API for some reason, we should think about changing them in the schema.
Oskar

**Comment by odungern** [comment]
I guess we will be talking about:
- hyphenated vs. camelCase (data-types or dataTypes)
- big vs. small initial (DataTypes or dataTypes)
- have the revision in the URL or as a query parameter
- singular vs. plural (resource vs. resources). We could say (even though I have never seen it in real life) use plural, if we request or supply a list, e.g. PUT .../dataType**s** to supply a list of several dataTypes while GET/PUT .../dataType/{id} requests/updates a single object. We need a solution for batch requests sooner or later, why make 3 calls, if we can supply 3 items in a single call.

**Comment by odungern** [comment]
Please have a look. I have finished (I think) all endpoints, but the data revisions are still to be reviewed. Also we will need quite some query parameters (I would say we need a query-structure, not just a flat list of query parameters, if that can be done), Let's see.

**Comment by odungern** [comment]
Please have a look (@oalt , @oeichmann , @S-Ruesch) . I have finished (I think) all endpoints, but the data revisions are still to be reviewed. Also we will need quite some query parameters (I would say we need a query-structure, not just a flat list of query parameters, if that can be done), Let's see.

**Comment by odungern** [comment]
Reality has overtaken.

**Pull request closed without merging**
